### PR TITLE
Added Catalan translation

### PR DESCRIPTION
**Pull request by themonti**
I have added the Catalan translation.

I have checked the syntax and execute test.

### CODE REVIEW

**Comment by justin-schroeder** [comment]
Awesome, thank you!

**Comment by justin-schroeder** [comment]
@themonti — Without getting political here — what flag would you like to display next to your translation on vueformulate.com? Is the Spanish flag acceptable? Normally we just use emoji to represent the country of origin of the translator — but I know the Catalan situation is a little more sticky than that (and while Catalonia has a flag, it does not have a emoji). Since you put in the work to do the translation I'll leave the final decision up to you. If you'd like we could use little png of the Catalonian flag.

**Comment by themonti** [comment]
Hi @justin-schroeder , I appreciate you asking me. The ideal would be to put the little png of the flag of Catalonia (https://es.wikipedia.org/wiki/Catalu%C3%B1a#/media/Archivo:Flag_of_Catalonia.svg).

Without going into politics, in Spain several languages are recognized in the country. On the official websites of the Spanish Government, the icon of the Spanish flag is used for "Spanish", the icon of the Catalan flag for "Catalan", and the icon of the Galician flag for "Galician".

And thanks for your work! Vue-formulate is amazing!!

**Comment by justin-schroeder** [comment]
Ok you got it. we'll have it bundled in the next release!

**Pull request merged**
